<footer>
    <div class="row">
        <hr />
        <ul class="breadcrumbs">
            <li class="unavailable"><p>&copy; 2013 Essense of Awesome Creamery</p></li>
            <li><a href="index.php"> Home</a></li>
            <li><a href="signup.php"> Sign Up</a></li>
            <li><a href="customize.php"> Order/Customize</a></li>
            <li><a href="about.php"> About Us</a></li>
            <li><a href="blog.php"> Blog</a></li>
            <li><a href="contact.php"> Contact Us</a></li>
            <!--<li><a href="nutrition.php"> Nutrition Facts</a></li> -->
        </ul>
    </div>
</footer>

</html>